/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.twu.biblioteca;

import java.util.ArrayList;
import java.util.List;

public class App {
    static final String WELCOME_MESSAGE = "Welcome to Biblioteca. Your one-stop-shop for great book titles in Bangalore!";

    public static void main(String[] args) {
        List<Book> books = new ArrayList<>();
        for (int i=1; i < 4; ++i) {
            String name = "Book" + i;
            String author = "Author" + i;
            String yearPublished = "Year" + i;

            Book book = new Book(name, author, yearPublished);

            books.add(book);
        }

        BookLibrary bookLibrary = new BookLibrary(books);

        Printer printer = new Printer(System.out);
        printer.print(WELCOME_MESSAGE);
        printer.print(bookLibrary);
    }
}
/*
BookLibrary contains Printer
Interactions should be on BookLibrary instead of BookLibraryPrinter
*/
